=== spicyjpeg/573in1/schema/metrics.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id":     "schema/metrics.json",

	"title": "Font metrics",
	"type":  "object",

	"required": [
		"spaceWidth",
		"tabWidth",
		"lineHeight",
		"baselineOffset",
		"characterSizes"
	],

	"properties":  {
		"spaceWidth": {
			"title":       "Space width",
			"description": "Width of the space character in pixels.",
			"type":        "integer",

			"minimum":   0,
			"maximum": 255
		},
		"tabWidth": {
			"title":       "Tab width",
			"description": "Width of the tab character in pixels.",
			"type":        "integer",

			"minimum":   0,
			"maximum": 255
		},
		"lineHeight": {
			"title":       "Line height",
			"description": "Height of each line in pixels, including any padding. Characters whose height is lower than this value will be aligned to the top of the line by default.",
			"type":        "integer",

			"minimum":   0,
			"maximum": 255
		},
		"baselineOffset": {
			"title":       "Baseline offset",
			"description": "Offset to add to the Y coordinate of each line. Can be negative.",
			"type":        "integer",

			"minimum": -128,
			"maximum":  127
		},

		"characterSizes": {
			"title":       "Character list",
			"description": "List of all glyphs in the font texture. Each entry's key must be a string containing a printable Unicode character. Only single-code-point characters are supported.",
			"type":        "object",

			"additionalProperties": false,

			"patternProperties": {
				"^[^\\u0000-\\u001f]$": {
					"title": "Character metrics",
					"type":  "object",

					"required": [
						"x",
						"y",
						"width",
						"height"
					],
					"additionalProperties": false,

					"properties": {
						"x": {
							"title":       "X offset",
							"description": "X coordinate of the glyph's top left corner within the font texture.",
							"type":        "integer",

							"minimum":   0,
							"maximum": 255
						},
						"y": {
							"title":       "Y offset",
							"description": "Y coordinate of the glyph's top left corner within the font texture.",
							"type":        "integer",

							"minimum":   0,
							"maximum": 255
						},
						"width": {
							"title":       "Character width",
							"description": "Width of the glyph in pixels.",
							"type":        "integer",

							"minimum":   0,
							"maximum": 127
						},
						"height": {
							"title":       "Character height",
							"description": "Height of the glyph in pixels.",
							"type":        "integer",

							"minimum":   0,
							"maximum": 127
						},
						"icon": {
							"title":       "Colored icon flag",
							"description": "If true, the glyph will not be colorized when drawing colored text. Useful for glyphs that are not monochrome such as icons or emoji.",
							"type":        "boolean"
						}
					}
				}
			}
		}
	}
}

=== spicyjpeg/573in1/assets/textures/font.json
{
	"$schema": "../../schema/metrics.json",

	"spaceWidth":      4,
	"tabWidth":       32,
	"lineHeight":     10,
	"baselineOffset": -1,

	"characterSizes": {
		" ":  { "x":  0, "y":  0, "width": 4, "height": 10 },
		"!":  { "x":  6, "y":  0, "width": 2, "height": 10 },
		"\"": { "x": 12, "y":  0, "width": 4, "height": 10 },
		"#":  { "x": 18, "y":  0, "width": 6, "height": 10 },
		"$":  { "x": 24, "y":  0, "width": 6, "height": 10 },
		"%":  { "x": 30, "y":  0, "width": 6, "height": 10 },
		"&":  { "x": 36, "y":  0, "width": 6, "height": 10 },
		"'":  { "x": 42, "y":  0, "width": 2, "height": 10 },
		"(":  { "x": 48, "y":  0, "width": 3, "height": 10 },
		")":  { "x": 54, "y":  0, "width": 3, "height": 10 },
		"*":  { "x": 60, "y":  0, "width": 4, "height": 10 },
		"+":  { "x": 66, "y":  0, "width": 6, "height": 10 },
		",":  { "x": 72, "y":  0, "width": 3, "height": 10 },
		"-":  { "x": 78, "y":  0, "width": 6, "height": 10 },
		".":  { "x": 84, "y":  0, "width": 2, "height": 10 },
		"/":  { "x": 90, "y":  0, "width": 6, "height": 10 },
		"0":  { "x":  0, "y": 10, "width": 6, "height": 10 },
		"1":  { "x":  6, "y": 10, "width": 6, "height": 10 },
		"2":  { "x": 12, "y": 10, "width": 6, "height": 10 },
		"3":  { "x": 18, "y": 10, "width": 6, "height": 10 },
		"4":  { "x": 24, "y": 10, "width": 6, "height": 10 },
		"5":  { "x": 30, "y": 10, "width": 6, "height": 10 },
		"6":  { "x": 36, "y": 10, "width": 6, "height": 10 },
		"7":  { "x": 42, "y": 10, "width": 6, "height": 10 },
		"8":  { "x": 48, "y": 10, "width": 6, "height": 10 },
		"9":  { "x": 54, "y": 10, "width": 6, "height": 10 },
		":":  { "x": 60, "y": 10, "width": 2, "height": 10 },
		";":  { "x": 66, "y": 10, "width": 3, "height": 10 },
		"<":  { "x": 72, "y": 10, "width": 6, "height": 10 },
		"=":  { "x": 78, "y": 10, "width": 6, "height": 10 },
		">":  { "x": 84, "y": 10, "width": 6, "height": 10 },
		"?":  { "x": 90, "y": 10, "width": 6, "height": 10 },
		"@":  { "x":  0, "y": 20, "width": 6, "height": 10 },
		"A":  { "x":  6, "y": 20, "width": 6, "height": 10 },
		"B":  { "x": 12, "y": 20, "width": 6, "height": 10 },
		"C":  { "x": 18, "y": 20, "width": 6, "height": 10 },
		"D":  { "x": 24, "y": 20, "width": 6, "height": 10 },
		"E":  { "x": 30, "y": 20, "width": 6, "height": 10 },
		"F":  { "x": 36, "y": 20, "width": 6, "height": 10 },
		"G":  { "x": 42, "y": 20, "width": 6, "height": 10 },
		"H":  { "x": 48, "y": 20, "width": 6, "height": 10 },
		"I":  { "x": 54, "y": 20, "width": 4, "height": 10 },
		"J":  { "x": 60, "y": 20, "width": 5, "height": 10 },
		"K":  { "x": 66, "y": 20, "width": 6, "height": 10 },
		"L":  { "x": 72, "y": 20, "width": 6, "height": 10 },
		"M":  { "x": 78, "y": 20, "width": 6, "height": 10 },
		"N":  { "x": 84, "y": 20, "width": 6, "height": 10 },
		"O":  { "x": 90, "y": 20, "width": 6, "height": 10 },
		"P":  { "x":  0, "y": 30, "width": 6, "height": 10 },
		"Q":  { "x":  6, "y": 30, "width": 6, "height": 10 },
		"R":  { "x": 12, "y": 30, "width": 6, "height": 10 },
		"S":  { "x": 18, "y": 30, "width": 6, "height": 10 },
		"T":  { "x": 24, "y": 30, "width": 6, "height": 10 },
		"U":  { "x": 30, "y": 30, "width": 6, "height": 10 },
		"V":  { "x": 36, "y": 30, "width": 6, "height": 10 },
		"W":  { "x": 42, "y": 30, "width": 6, "height": 10 },
		"X":  { "x": 48, "y": 30, "width": 6, "height": 10 },
		"Y":  { "x": 54, "y": 30, "width": 6, "height": 10 },
		"Z":  { "x": 60, "y": 30, "width": 6, "height": 10 },
		"[":  { "x": 66, "y": 30, "width": 3, "height": 10 },
		"\\": { "x": 72, "y": 30, "width": 6, "height": 10 },
		"]":  { "x": 78, "y": 30, "width": 3, "height": 10 },
		"^":  { "x": 84, "y": 30, "width": 4, "height": 10 },
		"_":  { "x": 90, "y": 30, "width": 6, "height": 10 },
		"`":  { "x":  0, "y": 40, "width": 3, "height": 10 },
		"a":  { "x":  6, "y": 40, "width": 6, "height": 10 },
		"b":  { "x": 12, "y": 40, "width": 6, "height": 10 },
		"c":  { "x": 18, "y": 40, "width": 6, "height": 10 },
		"d":  { "x": 24, "y": 40, "width": 6, "height": 10 },
		"e":  { "x": 30, "y": 40, "width": 6, "height": 10 },
		"f":  { "x": 36, "y": 40, "width": 5, "height": 10 },
		"g":  { "x": 42, "y": 40, "width": 6, "height": 10 },
		"h":  { "x": 48, "y": 40, "width": 5, "height": 10 },
		"i":  { "x": 54, "y": 40, "width": 2, "height": 10 },
		"j":  { "x": 60, "y": 40, "width": 4, "height": 10 },
		"k":  { "x": 66, "y": 40, "width": 5, "height": 10 },
		"l":  { "x": 72, "y": 40, "width": 2, "height": 10 },
		"m":  { "x": 78, "y": 40, "width": 6, "height": 10 },
		"n":  { "x": 84, "y": 40, "width": 5, "height": 10 },
		"o":  { "x": 90, "y": 40, "width": 6, "height": 10 },
		"p":  { "x":  0, "y": 50, "width": 6, "height": 10 },
		"q":  { "x":  6, "y": 50, "width": 6, "height": 10 },
		"r":  { "x": 12, "y": 50, "width": 6, "height": 10 },
		"s":  { "x": 18, "y": 50, "width": 6, "height": 10 },
		"t":  { "x": 24, "y": 50, "width": 5, "height": 10 },
		"u":  { "x": 30, "y": 50, "width": 5, "height": 10 },
		"v":  { "x": 36, "y": 50, "width": 6, "height": 10 },
		"w":  { "x": 42, "y": 50, "width": 6, "height": 10 },
		"x":  { "x": 48, "y": 50, "width": 6, "height": 10 },
		"y":  { "x": 54, "y": 50, "width": 6, "height": 10 },
		"z":  { "x": 60, "y": 50, "width": 5, "height": 10 },
		"{":  { "x": 66, "y": 50, "width": 4, "height": 10 },
		"|":  { "x": 72, "y": 50, "width": 2, "height": 10 },
		"}":  { "x": 78, "y": 50, "width": 4, "height": 10 },
		"~":  { "x": 84, "y": 50, "width": 6, "height": 10 },

		"\u00a0": { "x":  0, "y":  60, "width": 4, "height": 10 },
		"¡":      { "x":  6, "y":  60, "width": 2, "height": 10 },
		"¢":      { "x": 12, "y":  60, "width": 5, "height": 10 },
		"£":      { "x": 18, "y":  60, "width": 6, "height": 10 },
		"¤":      { "x": 24, "y":  60, "width": 6, "height": 10 },
		"¥":      { "x": 30, "y":  60, "width": 6, "height": 10 },
		"¦":      { "x": 36, "y":  60, "width": 2, "height": 10 },
		"§":      { "x": 42, "y":  60, "width": 5, "height": 10 },
		"¨":      { "x": 48, "y":  60, "width": 4, "height": 10 },
		"©":      { "x": 54, "y":  60, "width": 6, "height": 10 },
		"ª":      { "x": 60, "y":  60, "width": 4, "height": 10 },
		"«":      { "x": 66, "y":  60, "width": 6, "height": 10 },
		"¬":      { "x": 72, "y":  60, "width": 6, "height": 10 },
		"\u00ad": { "x": 78, "y":  60, "width": 4, "height": 10 },
		"®":      { "x": 84, "y":  60, "width": 6, "height": 10 },
		"¯":      { "x": 90, "y":  60, "width": 6, "height": 10 },
		"°":      { "x":  0, "y":  70, "width": 4, "height": 10 },
		"±":      { "x":  6, "y":  70, "width": 6, "height": 10 },
		"²":      { "x": 12, "y":  70, "width": 4, "height": 10 },
		"³":      { "x": 18, "y":  70, "width": 4, "height": 10 },
		"´":      { "x": 24, "y":  70, "width": 3, "height": 10 },
		"µ":      { "x": 30, "y":  70, "width": 5, "height": 10 },
		"¶":      { "x": 36, "y":  70, "width": 6, "height": 10 },
		"·":      { "x": 42, "y":  70, "width": 4, "height": 10 },
		"¸":      { "x": 48, "y":  70, "width": 5, "height": 10 },
		"¹":      { "x": 54, "y":  70, "width": 4, "height": 10 },
		"º":      { "x": 60, "y":  70, "width": 4, "height": 10 },
		"»":      { "x": 66, "y":  70, "width": 6, "height": 10 },
		"¼":      { "x": 72, "y":  70, "width": 6, "height": 10 },
		"½":      { "x": 78, "y":  70, "width": 6, "height": 10 },
		"¾":      { "x": 84, "y":  70, "width": 6, "height": 10 },
		"¿":      { "x": 90, "y":  70, "width": 6, "height": 10 },
		"À":      { "x":  0, "y":  80, "width": 6, "height": 10 },
		"Á":      { "x":  6, "y":  80, "width": 6, "height": 10 },
		"Â":      { "x": 12, "y":  80, "width": 6, "height": 10 },
		"Ã":      { "x": 18, "y":  80, "width": 6, "height": 10 },
		"Ä":      { "x": 24, "y":  80, "width": 6, "height": 10 },
		"Å":      { "x": 30, "y":  80, "width": 6, "height": 10 },
		"Æ":      { "x": 36, "y":  80, "width": 6, "height": 10 },
		"Ç":      { "x": 42, "y":  80, "width": 6, "height": 10 },
		"È":      { "x": 48, "y":  80, "width": 6, "height": 10 },
		"É":      { "x": 54, "y":  80, "width": 6, "height": 10 },
		"Ê":      { "x": 60, "y":  80, "width": 6, "height": 10 },
		"Ë":      { "x": 66, "y":  80, "width": 6, "height": 10 },
		"Ì":      { "x": 72, "y":  80, "width": 4, "height": 10 },
		"Í":      { "x": 78, "y":  80, "width": 4, "height": 10 },
		"Î":      { "x": 84, "y":  80, "width": 4, "height": 10 },
		"Ï":      { "x": 90, "y":  80, "width": 4, "height": 10 },
		"Ð":      { "x":  0, "y":  90, "width": 6, "height": 10 },
		"Ñ":      { "x":  6, "y":  90, "width": 6, "height": 10 },
		"Ò":      { "x": 12, "y":  90, "width": 6, "height": 10 },
		"Ó":      { "x": 18, "y":  90, "width": 6, "height": 10 },
		"Ô":      { "x": 24, "y":  90, "width": 6, "height": 10 },
		"Õ":      { "x": 30, "y":  90, "width": 6, "height": 10 },
		"Ö":      { "x": 36, "y":  90, "width": 6, "height": 10 },
		"×":      { "x": 42, "y":  90, "width": 6, "height": 10 },
		"Ø":      { "x": 48, "y":  90, "width": 6, "height": 10 },
		"Ù":      { "x": 54, "y":  90, "width": 6, "height": 10 },
		"Ú":      { "x": 60, "y":  90, "width": 6, "height": 10 },
		"Û":      { "x": 66, "y":  90, "width": 6, "height": 10 },
		"Ü":      { "x": 72, "y":  90, "width": 6, "height": 10 },
		"Ý":      { "x": 78, "y":  90, "width": 6, "height": 10 },
		"Þ":      { "x": 84, "y":  90, "width": 6, "height": 10 },
		"ß":      { "x": 90, "y":  90, "width": 6, "height": 10 },
		"à":      { "x":  0, "y": 100, "width": 6, "height": 10 },
		"á":      { "x":  6, "y": 100, "width": 6, "height": 10 },
		"â":      { "x": 12, "y": 100, "width": 6, "height": 10 },
		"ã":      { "x": 18, "y": 100, "width": 6, "height": 10 },
		"ä":      { "x": 24, "y": 100, "width": 6, "height": 10 },
		"å":      { "x": 30, "y": 100, "width": 6, "height": 10 },
		"æ":      { "x": 36, "y": 100, "width": 6, "height": 10 },
		"ç":      { "x": 42, "y": 100, "width": 6, "height": 10 },
		"è":      { "x": 48, "y": 100, "width": 6, "height": 10 },
		"é":      { "x": 54, "y": 100, "width": 6, "height": 10 },
